# frontend/Dockerfile
FROM nginx:alpine

# Copy the HTML files and assets from the frontend directory to the nginx html folder
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
